In [1]:
import numpy as np


>#  What is a Vector?
A **vector** is a quantity that has both **magnitude** and **direction**.

### Examples:
- Velocity (speed + direction)
- Force (magnitude + direction)

In mathematics, a vector can be represented as an **ordered list of numbers**, e.g.

$$ v = [2, 3, 4] $$

This represents a vector in **3D space**.

<br><br>
## Magnitude (Length) of a Vector

The **magnitude (or length)** of a vector represents how long the vector is — the distance from the origin to the point it defines.

For a vector:

$$
\mathbf{v} = 
\begin{bmatrix}
v_1 \\
v_2 \\
v_3
\end{bmatrix}
$$

The magnitude is given by:

$$
|\mathbf{v}| = \sqrt{v_1^2 + v_2^2 + v_3^2}
$$

### Example:
If  
$$
\mathbf{v} = 
\begin{bmatrix}
3 \\
4
\end{bmatrix}
$$

then  

$$
|\mathbf{v}| = \sqrt{3^2 + 4^2} = 5
$$



In [8]:
v = np.array([3, 4])
magnitude = np.linalg.norm(v)
print(magnitude)  

5.0


## Types of Vector

| **Type**           | **Description**                 | **Example**                                     |
| ------------------ | ------------------------------- | ----------------------------------------------- |
| Zero Vector        | All components are 0            | `[0, 0, 0]`                                     |
| Unit Vector        | Magnitude = 1                   | `[1, 0, 0]` or `[0, 1, 0]`                      |
| Equal Vectors      | Same direction & magnitude      | `[2, 3]` and `[2, 3]`                           |
| Negative Vectors   | Opposite direction              | `[2, 3]` and `[-2, -3]`                         |
| Parallel Vectors   | Same or opposite direction      | `[1, 2]` and `[2, 4]`                           |
| Orthogonal Vectors | Perpendicular (dot product = 0) | `[1, 0]` and `[0, 1]`                           |
| Position Vector    | Represents a point from origin  | `[x, y, z]`                                     |
| Row/Column Vector  | Representation type             | `[1, 2, 3]` (row) or `[[1], [2], [3]]` (column) |


In [3]:

v = np.array([2, 4, 6])          # Row vector
v_col = np.array([[1], [2], [3]]) # Column vector
zero_vec = np.zeros(3)            # Zero vector
unit_vec = np.array([1, 0])       # Unit vector example

print("Row Vector:", v)
print("Column Vector:\n", v_col)
print("Zero Vector:", zero_vec)
print("Unit Vector:", unit_vec)


Row Vector: [2 4 6]
Column Vector:
 [[1]
 [2]
 [3]]
Zero Vector: [0. 0. 0.]
Unit Vector: [1 0]


<br><br>
##  Vector Operations

| Operation | Description | Formula | Example |
|------------|--------------|----------|----------|
| Addition | Add corresponding elements | a + b | [1,2] + [3,4] = [4,6] |
| Subtraction | Subtract corresponding elements | a - b | [3,5] - [1,2] = [2,3] |
| Scalar Multiplication | Multiply each element by constant | k×v | 2×[1,2,3] = [2,4,6] |
| Dot Product | a₁b₁ + a₂b₂ + … | np.dot(a,b) | [1,2,3]·[4,5,6] = 32 |
| Magnitude | √(a₁² + a₂² + …) | np.linalg.norm(a) | [3,4] → 5 |

---


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
k = 2

print("a + b =", a + b)
print("a - b =", a - b)
print("k * a =", k * a)
print("Dot product =", np.dot(a, b))
print("Magnitude of a =", np.linalg.norm(a))


a + b = [5 7 9]
a - b = [-3 -3 -3]
k * a = [2 4 6]
Dot product = 32
Magnitude of a = 3.7416573867739413


## Properties of vector

| **Property**           | **Expression**            | **Description**                       |
| ---------------------- | ------------------------- | ------------------------------------- |
| Commutative            | a + b = b + a             | Order doesn’t matter in addition      |
| Associative            | (a + b) + c = a + (b + c) | Grouping doesn’t matter               |
| Distributive           | k(a + b) = ka + kb        | Scalar distributes                    |
| Zero Vector            | a + 0 = a                 | Adding zero doesn’t change the vector |
| Negative Vector        | a + (−a) = 0              | Cancels out                           |
| Magnitude Non-Negative | |a| ≥ 0                   | Vector length can’t be negative       |


<br><br><br><br>
> #  What is a Matrix?

A **matrix** is a **rectangular array of numbers** arranged in **rows and columns**.

Example:
$$
A = 
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

In NumPy:
```python
A = np.array([[1, 2, 3], [4, 5, 6]])


## Types of Matrix

| **Type**              | **Description**         | **Example**         |
| --------------------- | ----------------------- | ------------------- |
| Row Matrix            | Single row              | `[1, 2, 3]`         |
| Column Matrix         | Single column           | `[[1], [2], [3]]`   |
| Square Matrix         | Rows = Columns          | `[[1, 2], [3, 4]]`  |
| Zero Matrix           | All elements are 0      | `[[0, 0], [0, 0]]`  |
| Diagonal Matrix       | Non-diagonal = 0        | `[[5, 0], [0, 7]]`  |
| Scalar Matrix         | Diagonal elements equal | `[[3, 0], [0, 3]]`  |
| Identity Matrix (I)   | Diagonal = 1            | `[[1, 0], [0, 1]]`  |
| Symmetric Matrix      | A = Aᵀ                  | `[[1, 2], [2, 1]]`  |
| Skew-Symmetric Matrix | Aᵀ = −A                 | `[[0, 2], [-2, 0]]` |
| Upper Triangular      | Below diagonal = 0      | `[[1, 2], [0, 3]]`  |
| Lower Triangular      | Above diagonal = 0      | `[[1, 0], [4, 5]]`  |


In [5]:

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])
I = np.eye(2)  # Identity matrix
O = np.zeros((2, 2))  # Zero matrix

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Identity Matrix:\n", I)
print("Zero Matrix:\n", O)


Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[ 7  8  9]
 [10 11 12]]
Identity Matrix:
 [[1. 0.]
 [0. 1.]]
Zero Matrix:
 [[0. 0.]
 [0. 0.]]


##  Basic Matrix Operations

| Operation | Rule | Example |
|------------|------|----------|
| Addition | Same shape only | A + B |
| Subtraction | Same shape only | A - B |
| Scalar Multiplication | Multiply each element | 2×A |
| Transpose | Swap rows ↔ columns | Aᵀ |
| Matrix Multiplication | Inner dimensions must match | A(2×3) × B(3×2) |
| Determinant | Square matrices only | np.linalg.det(A) |
| Inverse | Square matrices only | np.linalg.inv(A) |

---


In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A + B =\n", A + B)
print("A - B =\n", A - B)
print("2 * A =\n", 2 * A)
print("Transpose of A =\n", A.T)
print("Matrix Multiplication (A x B) =\n", np.dot(A, B))
print("Determinant of A =", np.linalg.det(A))
print("Inverse of A =\n", np.linalg.inv(A))


A + B =
 [[ 6  8]
 [10 12]]
A - B =
 [[-4 -4]
 [-4 -4]]
2 * A =
 [[2 4]
 [6 8]]
Transpose of A =
 [[1 3]
 [2 4]]
Matrix Multiplication (A x B) =
 [[19 22]
 [43 50]]
Determinant of A = -2.0000000000000004
Inverse of A =
 [[-2.   1. ]
 [ 1.5 -0.5]]


#  Summary: Vectors & Matrices in Data Science and Machine Learning

##  What Are They?

- **Vectors** are **1D arrays** of numbers — they represent **features, directions, or data points**.  
  Example: `[height, weight, age] = [170, 65, 25]`

- **Matrices** are **2D arrays** of numbers — they store **multiple vectors together** or represent **linear transformations**.  
  Example: a dataset of 3 samples and 2 features:
  $$
  X = 
  \begin{bmatrix}
  170 & 65 \\
  160 & 55 \\
  180 & 75
  \end{bmatrix}
  $$

##  How to Use Them

- In Python (NumPy), vectors and matrices are created using:
  ```python
  import numpy as np
  
  v = np.array([2, 3, 4])          # Vector
  A = np.array([[1, 2], [3, 4]])   # Matrix
