# numpy
######  numpy ->(numerical python) -> wprks with numerical data
######  contain multidimensial arraty and data structure
######  contain high level of mathematical operations
######  why use numpy -> (in traditional puthon there is list (acts as array) .Numpy provide an array object which is 50x faster then list)
######  numpy provide a lot of supporting functions for ndarray

######  why numpy is fater -> (it stored array at one continuous place in memory so, process can access and manipulate .efficentily. The CPU cache can prefetch the next elements efficiently.) -> this is called locality of reference
######  In contrast, Python lists store references (pointers) to objects scattered across memory


In [3]:
import numpy as np

In [4]:
# making a numpy array using a list
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# making a numpy array using a tuple
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
#the answer we got will still be in the form of list

[1 2 3 4 5]
<class 'numpy.ndarray'>


<br><br>
<h1>Dimensions
<h3>ndim -> to check the dimension</h3>

In [ ]:
# zero dimension array
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


In [ ]:
# 1d array
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [ ]:
# 2d array
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [10]:
#can be floating numbers
arr = np.array([[1.3,2.3,3.6,4.7],[5.8,6.4,7.3,8]])
print(arr)
print(arr.ndim)

[[1.3 2.3 3.6 4.7]
 [5.8 6.4 7.3 8. ]]
2


In [17]:
# 3d array
arr = np.array([[[1,2,3,4],[5,6,7,8]] ,[[1,2,3,4],[5,6,7,8]]])
print(arr)
print(arr.ndim)


[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
3


In [ ]:
# creating a 5d array
arr= np.array([1,2,3,4] , ndmin=5)
print(arr)
print(f"dimension is : {arr.ndim}")


[[[[[1 2 3 4]]]]]
dimension is : 5


<br><br>
# numpy indexing (starting index is 0)

In [ ]:
# 1d indexing
arr= np.array([1,2,3,4,5,6,7,8,9])
print(f"zero index is {arr[0]}")
print(f"fifth index is {arr[4]}")
print(f"zero index to fifth index is {arr[0:4]}")
print(f"sum of zero index and fifth index {arr[0] + arr[4]}")

zero index is 1
fifth index is 5
zero index to fifth index is [1 2 3 4]
sum of zero index and fifth index 6


In [32]:
# 2d indexing  first row is 0 and second is 1
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(f"first element of first row {arr[0,0]}")
print(f"third element of first row {arr[0,2]}")
print(f"first element of second row {arr[1,0]}")
print(f"third element of second row {arr[1,2]}")
print(f"sum of first element of first row and third element of second row {arr[0,0] + arr[1,2]}")




first element of first row 1
third element of first row 3
first element of second row 5
third element of second row 7
sum of first element of first row and third element of second row 8


In [38]:
# 3d indexing  (first row zero and second row is 2 and (in inner also first row is 0 and second row is 1))
arr = np.array([[[1,2,3,4],[5,6,7,8]] ,[[9,10,11,12],[13,14,15,16]]])
print(f"printing 1 from 3d array: {arr[0,0,0]}")
print(f"printing 7 from 3d array: {arr[0,1,2]}")
print(f"printing 10 from 3d array: {arr[1,0,1]}")
print(f"printing 16 from 3d array: {arr[1,1,3]}")
print(f"sum of 7 and 16 is : {arr[0,1,2] + arr[1,1,3]}")



printing 1 from 3d array: 1
printing 7 from 3d array: 7
printing 10 from 3d array: 10
printing 16 from 3d array: 16
sum of 7 and 16 is : 23
