# slicing in numpy


In [1]:
import numpy as np

In [ ]:
#1d slicing
arr=np.array([10,20,30,40,50,60,70])
print(f"printing 20 to 50 : {arr[1:5]}")
print(f"skiping one number : {arr[::2]}")

printing 20 to 50 : [20 30 40 50]
akiping one number : [10 30 50 70]


In [8]:
#2d slicing
arr=np.array([[10,20,30,40,50,60,70] , [100,200,300,400,500,600,700]])
print(f"printing 20 to 50 : {arr[0,1:5]}")
print(f"skiping one number from secind row : {arr[1,::2]}")

printing 20 to 50 : [20 30 40 50]
skiping one number from secind row : [100 300 500 700]


In [16]:
#3d slicing
arr=np.array([[[1,2,3,4,5,6,7] ,[10,20,30,40,50,60,70] , [100,200,300,400,500,600,700]]])
print(f"printing 2 to 5 : {arr[0,0,1:5]}")
print(f"skiping one number from secind row : {arr[0,1,::2]}")
print(f"printing last two elements from 3rd row : {arr[0,2,5:7]}")

printing 2 to 5 : [2 3 4 5]
skiping one number from secind row : [10 30 50 70]
printing last two elements from 3rd row : [600 700]


In [11]:
#3d slicing
arr=np.array([[[1,2,3,4,5,6,7] , [12,34,66,77,88,99,65]] ,[[10,20,30,40,50,60,70] , [100,200,300,400,500,600,700]]])
print(f"printing 2 to 5 : {arr[0,0,1:5]}")
print(f"skiping one number from secind row : {arr[0,1,::2]}")
print(f"printing 10 to 50 : {arr[1,0,0:5]}")
print(f"skiping one number from fourth row : {arr[1,1,::2]}")

printing 2 to 5 : [2 3 4 5]
skiping one number from secind row : [12 66 88 65]
printing 10 to 50 : [10 20 30 40 50]
skiping one number from fourth row : [100 300 500 700]


<br><br>


# DataTypes in Numpy
Numpy have some extra datatypes
* i -- integer
* u -- unsigned integer
* b -- boolean
* f -- float
* c -- complete float
* M -- dateTime
* O -- object
* S -- string
* U -- unicode string
* V -- void

#### DataType can checked through dtype()


In [17]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [ ]:
arr=np.array(['lion' ,'panda','tiger'])
print(arr)
print(arr.dtype)

['lion' 'panda' 'tiger']
<U5


##### creating own datatype data

In [22]:
arr=np.array([1,2,3,4,5] , dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [ ]:
arr=np.array([1,2,3,4,5] , dtype='i4')    #i4 -> integer of 4 byte mean 32 bits
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [24]:
arr=np.array([1,2,3,4,5] , dtype='f')
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float32
