# Concatenate function
* used to join matrix along x or y axis means 0 or 1

In [ ]:
import numpy as np

# 1d concatenate
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr = np.concatenate((arr1 , arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# 2d concatenate on x axis
arr1 = np.array([[1,2,3,4,5] , [11,12,13,14,15]])
arr2 = np.array([[6,7,8,9,10] , [16,17,18,19,20]])
arr = np.concatenate((arr1 , arr2) , axis=1)
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [11]:
# 2d concatenate on y axis
arr1 = np.array([[1,2,3,4,5] , [11,12,13,14,15]])
arr2 = np.array([[6,7,8,9,10] , [16,17,18,19,20]])
arr = np.concatenate((arr1 , arr2) , axis=0)
print(arr)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [16 17 18 19 20]]


<br><br>
# Spliting


In [13]:
arr = np.array([1,2,3,4,5])
new_arr = np.array_split(arr ,2)
print(new_arr)

[array([1, 2, 3]), array([4, 5])]


In [15]:
arr = np.array([1,2,3,4,5,6,7,8])
new_arr = np.array_split(arr ,3)
print(new_arr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
