In [81]:
import numpy as np

### np.shape() -->to get to knew about the number of elements in dimension

In [82]:
# 1d
arr = np.array([1,2,3,4,5])
a = np.shape(arr)
print(a)

(5,)


In [83]:
# 2d array
arr = np.array([[1,2,3,4],[5,6,7,8]])
a= np.shape(arr)
print(a)


(2, 4)


In [84]:
# 3d array
arr = np.array([[[1,2,3,4],[5,6,7,8]] ,[[1,2,3,4],[5,6,7,8]]])
a = np.shape(arr)
print(a)

(2, 2, 4)


<br><br>
### Ravel and Flatten
* used to change any dimension to 1d

In [85]:
# 2d array
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(f"dimension before ravel is :{arr.ndim}")
r = np.ravel(arr)
print(r)
print(f"dimension after the ravel :{r.ndim}")


dimension before ravel is :2
[1 2 3 4 5 6 7 8]
dimension after the ravel :1


In [86]:
# 4d 
arr = np.array([[[[ [1,2,3,4,5] , [11,12,13,14,15] ,[1,2,3,4,5],[4,5,6,7,8] ]]]])
print(f"dimension before ravel is :{arr.ndim}")
r = np.ravel(arr)
print(r)
print(f"dimension after the ravel :{r.ndim}")


dimension before ravel is :5
[ 1  2  3  4  5 11 12 13 14 15  1  2  3  4  5  4  5  6  7  8]
dimension after the ravel :1


In [87]:
# 2d array
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(f"dimension before flatten is :{arr.ndim}")
arr.flatten()
print(arr)
print(f"dimension after the flatten :{r.ndim}")


dimension before flatten is :2
[[1 2 3 4]
 [5 6 7 8]]
dimension after the flatten :1


<br><br>
### Unique
* to get the unique elements from the array

In [88]:
arr = np.array([1,2,3,4,5,6,7,8,12,12,14,4,5,7,55])
u = np.unique(arr)
print(u)

[ 1  2  3  4  5  6  7  8 12 14 55]


In [89]:
# if also wants the index number
arr = np.array([1,2,3,4,5,6,7,8,12,12,14,4,5,7,55])
u = np.unique(arr ,return_index=True )
print(u)

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 12, 14, 55]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 14]))


In [90]:
# if also wants the index number and how much time a number repeats
arr = np.array([1,2,3,4,5,6,7,8,12,12,14,4,5,7,55])
u = np.unique(arr ,return_index=True , return_counts=True)
print(u)

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 12, 14, 55]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 14]), array([1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 1]))


<br><br>

### Delete

In [91]:
#deleting using index number
arr = np.array([1,2,3,4,5,6,7,8])
d = np.delete(arr , [0])              
print(d)

[2 3 4 5 6 7 8]


In [92]:
# delete multiple items
arr = np.array([1,2,3,4,5,6,7,8])
d = np.delete(arr , [1,4])        # remove index 1 and 4        
print(d)

[1 3 4 6 7 8]


In [93]:
# deleting entire row
arr = np.array([[[1,2,3,4,5] , [11,12,13,14,15] , [66,77,8,99,55]]])
d = np.delete(arr ,0 , axis=1)              
print(d)

[[[11 12 13 14 15]
  [66 77  8 99 55]]]


In [113]:
# deleting entire row
arr = np.array([[1,2,3,4,5] , [11,12,13,14,15], [11,22,33,44,55]])
d = np.delete(arr ,2 , axis=0)              
print(d)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


<br><br>
## Memory calculation

In [115]:
integers = np.array([
    [1, 3] , 
    [4,4]
])

print(integers.size)
print(integers.itemsize)
print("memory = ",integers.size * integers.itemsize)

4
8
memory =  32


<br><br>
## Fill with specific values

> zeros,
>ones,
>full

In [116]:
np.zeros(10 ,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [117]:
np.ones(10 , dtype= float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [120]:
# can also gives the dimension
np.full((3,5) , 2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

<br><br>
## arange
* to generate specific numbers

In [123]:
np.arange(10,20,  dtype=float)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

<br><br>
## reshape
* to change the dimension 

In [139]:
arr = np.arange(1,21)
print(arr)
print()
arr1=np.arange(1,21).reshape(4,5)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


<br><br>
## universal functions


In [140]:
grades = np.array([
    [44 ,66 ,88] , 
    [56,34,22],
    [88,87,45]
])
grades

array([[44, 66, 88],
       [56, 34, 22],
       [88, 87, 45]])

In [141]:
print(grades.sum())
print(grades.min())
print(grades.max())
print(grades.std())
print(grades.var())

530
22
88
23.425742935897794
548.7654320987654


In [142]:
# axis 0 is for horizontal rows
grades.mean(axis=0)

array([62.66666667, 62.33333333, 51.66666667])

In [143]:
# axis 1 is for columns vertically
grades.mean(axis=1)

array([66.        , 37.33333333, 73.33333333])

In [144]:
x=[1,2,3,4,5,6]
y=[2,3,4,5,6,7]

print(np.multiply(x ,y))
print(np.add(x,y))


[ 2  6 12 20 30 42]
[ 3  5  7  9 11 13]


In [162]:
# array operators

numbers = np.arange(1,10)
print("simple numbers                     ",numbers)
print("after multiplying with 2           ",numbers * 2)
print("after adding 4 in each             ",numbers + 4)
print("after double multiplying with each ",numbers ** 2)


simple numbers                      [1 2 3 4 5 6 7 8 9]
after multiplying with 2            [ 2  4  6  8 10 12 14 16 18]
after adding 4 in each              [ 5  6  7  8  9 10 11 12 13]
after double multiplying with each  [ 1  4  9 16 25 36 49 64 81]
